version: '2'
services:

  postgres:
    image: postgres
    restart: always
    ports:
      - 5438:5432
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "postgres"
    network_mode: "bridge"
    #command: postgres -c 'max_connections=100'


  adminer:
    image: adminer
    restart: always
    ports:
      - 9081:8080
    depends_on:
      - postgres
    links:
      - postgres
    network_mode: "bridge"

  api-service:
    build: .
    ports:
      - "7878:7878"
      - "8005:8005"
    depends_on:
      - postgres
    links:
      - postgres
    network_mode: "bridge"
    #command: java -jar -Dspring.profiles.active=localdocker /api.jar
